using System.Text;
using Phi.Compiler.Semantics;
using Phi.Compiler.Syntax;

namespace Phi.Compiler.CodeGen
{
    public sealed class AsmUnit
    {
        public UnitKind Kind { get; init; }
        public string Name { get; init; } = "";
        public string Text { get; init; } = "";
    }

    /// <summary>
    /// Generates 16-bit real-mode NASM source. Values are computed in eax (32-bit registers
    /// work fine in real mode); every variable lives at a fixed label. Library routines may
    /// change any general-purpose register, so nothing is kept in registers between statements.
    /// </summary>
    public sealed class X86_16Generator
    {
        public const string Target = "x86_16";

        /// <summary>Where the boot sector loads the kernel; also the first address the BIOS doesn't use.</summary>
        public const int KernelAddress = 0x7E00;

        readonly BoundProgram program;
        readonly BoundUnit unit;
        readonly DiagnosticBag diagnostics;

        readonly StringBuilder code = new();
        readonly HashSet<string> librarySymbols = new();
        readonly Dictionary<string, string> stringLabels = new();
        int labelCount;
        int lastCommentLine = -1;

        X86_16Generator(BoundProgram program, BoundUnit unit, DiagnosticBag diagnostics)
        {
            this.program = program;
            this.unit = unit;
            this.diagnostics = diagnostics;
        }

        public static AsmUnit Generate(BoundProgram program, BoundUnit unit, DiagnosticBag diagnostics)
        {
            var gen = new X86_16Generator(program, unit, diagnostics);
            return new AsmUnit
            {
                Kind = unit.Kind,
                Name = unit.Kind == UnitKind.Boot ? "boot" : "kernel",
                Text = gen.Build(),
            };
        }

        // ================================================================ layout

        string Build()
        {
            bool boot = unit.Kind == UnitKind.Boot;
            var output = new StringBuilder();

            output.AppendLine($"; {(boot ? "Boot sector" : "Kernel")} generated by phi from {Path.GetFileName(program.File.Path)}");
            output.AppendLine("bits 16");

            if (boot)
            {
                output.AppendLine("org 0x7C00");
                output.AppendLine();
                output.AppendLine("%ifndef PHI_KERNEL_SECTORS");
                output.AppendLine("%define PHI_KERNEL_SECTORS 0");
                output.AppendLine("%endif");
                output.AppendLine();
                output.AppendLine("    jmp 0x0000:phi_start    ; some BIOSes start us at 07C0:0000");
                output.AppendLine("phi_start:");
                output.AppendLine("    cli");
                output.AppendLine("    xor ax, ax");
                output.AppendLine("    mov ds, ax");
                output.AppendLine("    mov es, ax");
                output.AppendLine("    mov ss, ax");
                output.AppendLine("    mov sp, 0x7C00          ; the stack grows down from just below us");
                output.AppendLine("    sti");
                output.AppendLine("    cld");
                output.AppendLine("    mov [phi_boot_drive], dl");
            }
            else
            {
                output.AppendLine($"org 0x{KernelAddress:X}");
                output.AppendLine();
                output.AppendLine("phi_start:");
                output.AppendLine("    cld");
            }

            // main program: class bodies in order
            foreach (ClassDecl cls in unit.Classes)
            {
                Comment($"---- class {cls.Name}");
                foreach (Stmt s in cls.Body) EmitStatement(s);
            }

            Line("");
            Label("phi_halt");
            Emit("hlt");
            Emit("jmp phi_halt");

            foreach (MethodSymbol m in unit.Methods) EmitMethod(m);
            foreach (RawBlockDecl raw in unit.RawBlocks) EmitRawBlock(raw);

            List<LibraryFile> library = Library.Resolve(Target, librarySymbols.OrderBy(s => s));

            // events used by the library that the program doesn't handle
            var defined = unit.Methods.Select(m => m.Label).ToHashSet();
            foreach (string hook in library.SelectMany(f => f.Hooks).Distinct().Where(h => !defined.Contains(h)))
            {
                Line("");
                Label(hook);
                Emit("ret");
            }

            output.Append(code);

            foreach (LibraryFile file in library)
            {
                output.AppendLine();
                output.AppendLine($"; ---- library: {file.Name}");
                output.Append(file.Text);
            }

            output.AppendLine();
            output.AppendLine("; ---- data");
            EmitData(output);

            if (boot)
            {
                output.AppendLine("phi_boot_drive: db 0");
                output.AppendLine();
                output.AppendLine("times 510 - ($ - $$) db 0   ; a negative size here means the boot sector is too big");
                output.AppendLine("dw 0xAA55");
            }

            return output.ToString();
        }

        // ================================================================ emit helpers

        void Emit(string instruction) => code.Append("    ").AppendLine(instruction);
        void Label(string label) => code.Append(label).AppendLine(":");
        void Line(string text) => code.AppendLine(text);
        string NewLabel(string hint) => $"phi_{hint}_{labelCount++}";

        void Comment(string text) => code.Append("    ; ").AppendLine(text);

        /// <summary>Puts the source line above the code it produced, which helps when reading the .asm.</summary>
        void SourceComment(Node node)
        {
            var (line, _) = program.File.GetLocation(node.Span.Start);
            if (line == lastCommentLine) return;
            lastCommentLine = line;

            string[] lines = program.File.Text.Split('\n');
            string text = line - 1 < lines.Length ? lines[line - 1].Trim() : "";
            code.AppendLine($"    ; {line}: {text}");
        }

        void Need(string librarySymbol) => librarySymbols.Add(librarySymbol);

        string StringLabel(string value)
        {
            if (!stringLabels.TryGetValue(value, out string? label))
            {
                label = $"phi_string_{stringLabels.Count}";
                stringLabels[value] = label;
            }
            return label;
        }

        // ================================================================ methods and asm blocks

        void EmitMethod(MethodSymbol m)
        {
            Line("");
            if (m.IsHook) Comment($"event {m.Name}");
            else Comment($"method {m.Name}");
            Label(m.Label);

            foreach (Stmt s in m.Decl.Body) EmitStatement(s);

            if (m.Decl.Result != null)
            {
                SourceComment(m.Decl.Result);
                EmitExpr(m.Decl.Result); // the result goes back in eax
            }

            Emit("ret");
        }

        void EmitRawBlock(RawBlockDecl raw)
        {
            var variables = unit.Variables.Where(v => !v.IsLocal).GroupBy(v => v.Name).ToDictionary(g => g.Key, g => g.First());

            Line("");
            Comment($"asm.{raw.Name}");
            Label(raw.Name);

            var text = new StringBuilder();
            int i = 0;
            while (i < raw.Text.Length)
            {
                int open = raw.Text.IndexOf('{', i);
                if (open < 0) { text.Append(raw.Text, i, raw.Text.Length - i); break; }

                int close = raw.Text.IndexOf('}', open);
                if (close < 0) { text.Append(raw.Text, i, raw.Text.Length - i); break; }

                text.Append(raw.Text, i, open - i);
                string name = raw.Text[(open + 1)..close].Trim();

                if (variables.TryGetValue(name, out VariableSymbol? v))
                    text.Append(v.Label);
                else
                    diagnostics.Error(program.File, new Span(raw.TextSpan.Start + open, close - open + 1),
                        $"asm.{raw.Name} uses {{{name}}}, but there is no class variable named '{name}'");

                i = close + 1;
            }

            foreach (string line in text.ToString().Replace("\r\n", "\n").Split('\n'))
                Line(line.TrimEnd());
        }

        // ================================================================ statements

        void EmitStatement(Stmt stmt)
        {
            if (stmt is not VarDecl { Symbol.NeedsInitCode: false }) SourceComment(stmt);

            switch (stmt)
            {
                case VarDecl decl:
                    if (decl.Symbol is { NeedsInitCode: true } declared) EmitInitialize(declared, decl.Values);
                    break;

                case LogStmt log:
                    EmitLog(log);
                    break;

                case AskStmt ask:
                {
                    var v = (VariableSymbol)ask.Target.Symbol!;
                    Need("phi_read_line");
                    Emit($"mov di, {v.Label}");
                    Emit($"mov cx, {v.Capacity - 1}");
                    Emit("call phi_read_line");
                    break;
                }

                case ExitStmt exit:
                    if (exit.Code != null) EmitExpr(exit.Code);
                    else Emit("xor eax, eax");
                    Emit("mov dx, 0xF4            ; QEMU isa-debug-exit");
                    Emit("out dx, al");
                    Emit("jmp phi_halt            ; not running in QEMU");
                    break;

                case CallStmt call:
                    EmitCall(call);
                    break;

                case IfStmt ifs:
                {
                    string elseLabel = NewLabel("else");
                    string endLabel = NewLabel("endif");

                    EmitBranch(ifs.Condition, jumpIf: false, ifs.Else != null ? elseLabel : endLabel);
                    foreach (Stmt s in ifs.Then) EmitStatement(s);

                    if (ifs.Else != null)
                    {
                        Emit($"jmp {endLabel}");
                        Label(elseLabel);
                        foreach (Stmt s in ifs.Else) EmitStatement(s);
                    }

                    Label(endLabel);
                    break;
                }

                case WhileStmt loop:
                {
                    if (loop.Init?.Symbol != null) EmitInitialize(loop.Init.Symbol, loop.Init.Values);

                    string top = NewLabel("while");
                    string end = NewLabel("endwhile");

                    Label(top);
                    EmitBranch(loop.Condition, jumpIf: false, end);
                    foreach (Stmt s in loop.Body) EmitStatement(s);
                    if (loop.Step != null) EmitStatement(loop.Step);
                    Emit($"jmp {top}");
                    Label(end);
                    break;
                }

                case AssignStmt assign:
                    EmitAssign(assign.Target, assign.Value);
                    break;

                default:
                    throw new InvalidOperationException($"unexpected statement {stmt.GetType().Name}");
            }
        }

        void EmitInitialize(VariableSymbol v, List<Expr> values)
        {
            if (!v.Type.IsArray)
            {
                if (values.Count > 0) EmitAssign(new NameExpr { Name = v.Name, Symbol = v, Type = v.Type }, values[0]);
                return;
            }

            for (int i = 0; i < values.Count; i++)
            {
                var element = new IndexExpr
                {
                    Target = new NameExpr { Name = v.Name, Symbol = v, Type = v.Type },
                    Index = new NumberExpr { Value = i, Type = PhiType.Int },
                    Type = v.Type.Element,
                };
                EmitAssign(element, values[i]);
            }
        }

        void EmitLog(LogStmt log)
        {
            bool serialOnly = log.Target == LogTarget.SerialOnly;
            string printString = serialOnly ? "phi_print_serial" : "phi_print";
            string printInt = serialOnly ? "phi_print_int_serial" : "phi_print_int";

            foreach (Expr value in log.Values)
            {
                if (value.Type.IsString)
                {
                    Need(printString);
                    if (AddressOf(value) is string label) Emit($"mov si, {label}");
                    else
                    {
                        EmitExpr(value);
                        Emit("mov si, ax");
                    }
                    Emit($"call {printString}");
                }
                else
                {
                    Need(printInt);
                    EmitExpr(value);
                    Emit($"call {printInt}");
                }
            }
        }

        /// <summary>The label of a string whose address is known without running code.</summary>
        string? AddressOf(Expr e) => e switch
        {
            StringExpr s => StringLabel(s.Value),
            NameExpr { Symbol: VariableSymbol { Type.IsString: true } v } => v.Label,
            _ => null,
        };

        void EmitCall(CallStmt call)
        {
            switch (call.Resolved)
            {
                case MethodSymbol method:
                {
                    // parameters are variables of the method: set each one, using its default when no argument is given
                    for (int i = 0; i < method.Parameters.Count; i++)
                    {
                        VariableSymbol p = method.Parameters[i];
                        Expr? value = i < call.Arguments.Count ? call.Arguments[i] : p.Decl.Values.FirstOrDefault();
                        if (value != null) EmitAssign(new NameExpr { Name = p.Name, Symbol = p, Type = p.Type }, value);
                    }
                    Emit($"call {method.Label}");
                    if (call.ResultTarget != null) EmitStoreResult(call.ResultTarget, method.ReturnType);
                    break;
                }

                case BuiltinFunction builtin:
                {
                    for (int i = call.Arguments.Count - 1; i >= 0; i--)
                    {
                        EmitExpr(call.Arguments[i]);
                        Emit("push eax");
                    }
                    Need(builtin.Label);
                    Emit($"call {builtin.Label}");
                    if (call.Arguments.Count > 0) Emit($"add sp, {call.Arguments.Count * 4}");
                    if (call.ResultTarget != null) EmitStoreResult(call.ResultTarget, PhiType.Int);
                    break;
                }

                case RawBlockDecl raw:
                    Emit($"call {raw.Name}");
                    if (call.ResultTarget != null) EmitStoreResult(call.ResultTarget, PhiType.Int);
                    break;
            }
        }

        /// <summary>Stores a call result (in eax) into a variable.</summary>
        void EmitStoreResult(Expr target, PhiType resultType)
        {
            if (target.Type.IsString) EmitStringStore(target, sourceIsString: resultType.IsString);
            else EmitStoreEax(target);
        }

        // ================================================================ assignment

        void EmitAssign(Expr target, Expr value)
        {
            if (target.Type.IsString)
            {
                EmitExpr(value);
                EmitStringStore(target, sourceIsString: value.Type.IsString);
                return;
            }

            EmitExpr(value);
            EmitStoreEax(target);
        }

        /// <summary>Stores eax into a number variable or element.</summary>
        void EmitStoreEax(Expr target)
        {
            switch (target)
            {
                case NameExpr { Symbol: VariableSymbol v }:
                    Emit(v.Type.Kind == TypeKind.Int ? $"mov [{v.Label}], eax" : $"mov [{v.Label}], al");
                    break;

                case IndexExpr { Target: NameExpr { Symbol: VariableSymbol v } } index:
                    Emit("push eax");
                    EmitExpr(index.Index);
                    Emit("mov ebx, eax");
                    Emit("pop eax");
                    if (v.Type.IsArray && v.Type.Kind == TypeKind.Int) Emit($"mov [{v.Label} + ebx*4], eax");
                    else Emit($"mov [{v.Label} + ebx], al"); // byte arrays, and a character of a str
                    break;

                default:
                    throw new InvalidOperationException("unassignable target");
            }
        }

        /// <summary>
        /// eax holds a string address (sourceIsString) or a number to write out as text;
        /// put it in a str variable or str array element, cut to fit.
        /// </summary>
        void EmitStringStore(Expr target, bool sourceIsString)
        {
            VariableSymbol v;
            switch (target)
            {
                case NameExpr { Symbol: VariableSymbol nv }:
                    v = nv;
                    Emit($"mov di, {v.Label}");
                    break;

                case IndexExpr { Target: NameExpr { Symbol: VariableSymbol av } } index:
                    v = av;
                    Emit("push eax");
                    EmitExpr(index.Index);
                    Emit("mov ebx, eax");
                    Emit("pop eax");
                    Emit($"mov di, [{v.Label} + ebx*2]");
                    break;

                default:
                    throw new InvalidOperationException("unassignable target");
            }

            Emit($"mov cx, {v.Capacity}");
            if (sourceIsString)
            {
                Need("phi_strcpy");
                Emit("mov si, ax");
                Emit("call phi_strcpy");
            }
            else
            {
                Need("phi_int_to_str");
                Emit("call phi_int_to_str");
            }
        }

        // ================================================================ expressions

        /// <summary>Leaves the value of <paramref name="e"/> in eax (strings: their address).</summary>
        void EmitExpr(Expr e)
        {
            if (e is BinaryExpr or UnaryExpr && ConstantFolder.Evaluate(e) is long folded)
            {
                LoadConstant("eax", folded);
                return;
            }

            switch (e)
            {
                case NumberExpr n:
                    LoadConstant("eax", n.Value);
                    break;

                case BoolExpr b:
                    LoadConstant("eax", b.Value ? 1 : 0);
                    break;

                case StringExpr s:
                    Emit($"mov eax, {StringLabel(s.Value)}");
                    break;

                case NameExpr name:
                    EmitName(name);
                    break;

                case IndexExpr index:
                {
                    var v = (VariableSymbol)((NameExpr)index.Target).Symbol!;
                    EmitExpr(index.Index);
                    if (!v.Type.IsArray) Emit($"movzx eax, byte [{v.Label} + eax]"); // a character of a str
                    else if (v.Type.Kind == TypeKind.Int) Emit($"mov eax, [{v.Label} + eax*4]");
                    else if (v.Type.Kind == TypeKind.Str) Emit($"movzx eax, word [{v.Label} + eax*2]");
                    else Emit($"movzx eax, byte [{v.Label} + eax]");
                    break;
                }

                case UnaryExpr unary:
                    EmitExpr(unary.Operand);
                    if (unary.Op == UnaryOp.Negate) Emit("neg eax");
                    else
                    {
                        Emit("test eax, eax");
                        Emit("sete al");
                        Emit("movzx eax, al");
                    }
                    break;

                case BinaryExpr { IsComparison: true } or BinaryExpr { IsLogical: true }:
                {
                    string falseLabel = NewLabel("false");
                    string endLabel = NewLabel("bool");
                    EmitBranch(e, jumpIf: false, falseLabel);
                    Emit("mov eax, 1");
                    Emit($"jmp {endLabel}");
                    Label(falseLabel);
                    Emit("xor eax, eax");
                    Label(endLabel);
                    break;
                }

                case BinaryExpr binary:
                    EmitOperands(binary);
                    switch (binary.Op)
                    {
                        case BinaryOp.Add: Emit("add eax, ecx"); break;
                        case BinaryOp.Subtract: Emit("sub eax, ecx"); break;
                        case BinaryOp.Multiply: Emit("imul eax, ecx"); break;
                        case BinaryOp.Divide:
                            Emit("cdq");
                            Emit("idiv ecx");
                            break;
                        case BinaryOp.Modulo:
                            Emit("cdq");
                            Emit("idiv ecx");
                            Emit("mov eax, edx");
                            break;
                    }
                    break;

                default:
                    throw new InvalidOperationException($"unexpected expression {e.GetType().Name}");
            }
        }

        void EmitName(NameExpr name)
        {
            switch (name.Symbol)
            {
                case VariableSymbol v when v.Type.IsString:
                    Emit($"mov eax, {v.Label}");
                    break;
                case VariableSymbol v when v.Type.Kind == TypeKind.Int:
                    Emit($"mov eax, [{v.Label}]");
                    break;
                case VariableSymbol v:
                    Emit($"movzx eax, byte [{v.Label}]");
                    break;
                case ConstantSymbol k:
                    LoadConstant("eax", k.Value);
                    break;
                case LengthSymbol { Of: var of } when of.Type.IsArray:
                    LoadConstant("eax", of.Count);
                    break;
                case LengthSymbol { Of: var of }:
                    Need("phi_strlen");
                    Emit($"mov si, {of.Label}");
                    Emit("call phi_strlen");
                    break;
                default:
                    throw new InvalidOperationException($"unresolved name {name.Name}");
            }
        }

        void LoadConstant(string register, long value)
        {
            if (value == 0) Emit($"xor {register}, {register}");
            else Emit($"mov {register}, {(int)value}");
        }

        /// <summary>Left operand in eax, right operand in ecx.</summary>
        void EmitOperands(BinaryExpr b)
        {
            if (TryLoadSimple(b.Right, "ecx", dryRun: true))
            {
                EmitExpr(b.Left);
                TryLoadSimple(b.Right, "ecx", dryRun: false);
                return;
            }

            EmitExpr(b.Right);
            Emit("push eax");
            EmitExpr(b.Left);
            Emit("pop ecx");
        }

        /// <summary>Loads values that need no other registers straight into a register.</summary>
        bool TryLoadSimple(Expr e, string register, bool dryRun)
        {
            string? instruction = e switch
            {
                NumberExpr n => n.Value == 0 ? $"xor {register}, {register}" : $"mov {register}, {(int)n.Value}",
                BoolExpr b => $"mov {register}, {(b.Value ? 1 : 0)}",
                StringExpr s => $"mov {register}, {StringLabel(s.Value)}",
                NameExpr { Symbol: ConstantSymbol k } => $"mov {register}, {(int)k.Value}",
                NameExpr { Symbol: LengthSymbol { Of.Type.IsArray: true } len } => $"mov {register}, {len.Of.Count}",
                NameExpr { Symbol: VariableSymbol v } when v.Type.IsString => $"mov {register}, {v.Label}",
                NameExpr { Symbol: VariableSymbol { Type.IsArray: false } v } when v.Type.Kind == TypeKind.Int => $"mov {register}, [{v.Label}]",
                NameExpr { Symbol: VariableSymbol { Type.IsArray: false } v } => $"movzx {register}, byte [{v.Label}]",
                _ => null,
            };

            if (instruction == null) return false;
            if (!dryRun) Emit(instruction);
            return true;
        }

        /// <summary>Jumps to <paramref name="target"/> when the condition's truth equals <paramref name="jumpIf"/>.</summary>
        void EmitBranch(Expr condition, bool jumpIf, string target)
        {
            if (ConstantFolder.Evaluate(condition) is long known)
            {
                if ((known != 0) == jumpIf) Emit($"jmp {target}");
                return;
            }

            switch (condition)
            {
                case UnaryExpr { Op: UnaryOp.Not } not:
                    EmitBranch(not.Operand, !jumpIf, target);
                    return;

                case BinaryExpr { Op: BinaryOp.And } and:
                    if (jumpIf)
                    {
                        string skip = NewLabel("and");
                        EmitBranch(and.Left, false, skip);
                        EmitBranch(and.Right, true, target);
                        Label(skip);
                    }
                    else
                    {
                        EmitBranch(and.Left, false, target);
                        EmitBranch(and.Right, false, target);
                    }
                    return;

                case BinaryExpr { Op: BinaryOp.Or } or:
                    if (jumpIf)
                    {
                        EmitBranch(or.Left, true, target);
                        EmitBranch(or.Right, true, target);
                    }
                    else
                    {
                        string skip = NewLabel("or");
                        EmitBranch(or.Left, true, skip);
                        EmitBranch(or.Right, false, target);
                        Label(skip);
                    }
                    return;

                case BinaryExpr { IsComparison: true, Left.Type.IsString: true, Right.Type.IsString: true } cmp:
                {
                    Need("phi_strcmp");
                    EmitExpr(cmp.Right);
                    Emit("push eax");
                    EmitExpr(cmp.Left);
                    Emit("mov si, ax");
                    Emit("pop edi");
                    Emit("call phi_strcmp          ; eax = 0 when equal");
                    Emit("test eax, eax");
                    bool equalWanted = (cmp.Op == BinaryOp.Equal) == jumpIf;
                    Emit($"{(equalWanted ? "jz" : "jnz")} {target}");
                    return;
                }

                case BinaryExpr { IsComparison: true } cmp:
                {
                    EmitOperands(cmp);
                    Emit("cmp eax, ecx");
                    BinaryOp op = jumpIf ? cmp.Op : Invert(cmp.Op);
                    string jump = op switch
                    {
                        BinaryOp.Equal => "je",
                        BinaryOp.NotEqual => "jne",
                        BinaryOp.Less => "jl",
                        BinaryOp.LessEqual => "jle",
                        BinaryOp.Greater => "jg",
                        _ => "jge",
                    };
                    Emit($"{jump} {target}");
                    return;
                }
            }

            EmitExpr(condition);
            Emit("test eax, eax");
            Emit($"{(jumpIf ? "jnz" : "jz")} {target}");
        }

        static BinaryOp Invert(BinaryOp op) => op switch
        {
            BinaryOp.Equal => BinaryOp.NotEqual,
            BinaryOp.NotEqual => BinaryOp.Equal,
            BinaryOp.Less => BinaryOp.GreaterEqual,
            BinaryOp.LessEqual => BinaryOp.Greater,
            BinaryOp.Greater => BinaryOp.LessEqual,
            _ => BinaryOp.Less,
        };

        // ================================================================ data

        void EmitData(StringBuilder output)
        {
            foreach (VariableSymbol v in unit.Variables.Distinct())
            {
                if (v.Type.IsError) continue;
                output.Append(DataFor(v));
            }

            foreach (var (value, label) in stringLabels)
                output.AppendLine($"{label}: db {NasmBytes(value)}");
        }

        string DataFor(VariableSymbol v)
        {
            var sb = new StringBuilder();
            List<object>? values = v.StaticValues;
            PhiType t = v.Type;

            if (t.IsString)
            {
                string text = values is [var first] ? AsText(first) : "";
                AppendString(sb, v.Label, text, v.Capacity);
                return sb.ToString();
            }

            if (t.IsArray && t.Kind == TypeKind.Str)
            {
                var pointers = new List<string>();
                for (int i = 0; i < v.Count; i++)
                {
                    string element = $"{v.Label}__{i}";
                    pointers.Add(element);
                    string text = values != null && i < values.Count ? AsText(values[i]) : "";
                    AppendString(sb, element, text, v.Capacity);
                }
                sb.AppendLine($"{v.Label}: dw {string.Join(", ", pointers)}");
                return sb.ToString();
            }

            string directive = t.Kind == TypeKind.Int ? "dd" : "db";
            if (values == null || values.Count == 0)
            {
                sb.AppendLine(v.Count == 1 ? $"{v.Label}: {directive} 0" : $"{v.Label}: times {v.Count} {directive} 0");
                return sb.ToString();
            }

            var numbers = values.Select(x => x is long n ? n : 0).Select(n => t.Kind == TypeKind.Int ? ((int)n).ToString() : (n & 0xFF).ToString());
            sb.AppendLine($"{v.Label}: {directive} {string.Join(", ", numbers)}");
            return sb.ToString();
        }

        /// <summary>A constant destined for a str: text as-is, numbers written in decimal.</summary>
        static string AsText(object value) => value switch
        {
            string s => s,
            long n => ((int)n).ToString(),
            _ => "",
        };

        void AppendString(StringBuilder sb, string label, string text, int capacity)
        {
            if (text.Length + 1 > capacity) text = text[..Math.Max(capacity - 1, 0)];
            sb.AppendLine($"{label}: db {NasmBytes(text)}");
            int padding = capacity - text.Length - 1;
            if (padding > 0) sb.AppendLine($"    times {padding} db 0");
        }

        /// <summary>'Hello', 13, 10, 0 — printable text quoted, everything else as numbers.</summary>
        static string NasmBytes(string text)
        {
            var parts = new List<string>();
            var run = new StringBuilder();

            void Flush()
            {
                if (run.Length == 0) return;
                parts.Add($"'{run}'");
                run.Clear();
            }

            foreach (char c in text)
            {
                if (c >= 0x20 && c < 0x7F && c != '\'') run.Append(c);
                else
                {
                    Flush();
                    parts.Add(c < 256 ? ((int)c).ToString() : "'?'");
                }
            }

            Flush();
            parts.Add("0");
            return string.Join(", ", parts);
        }
    }
}
