using System.Text;
using Phi.Compiler.Semantics;
using Phi.Compiler.Syntax;

namespace Phi.Compiler.CodeGen
{
    public sealed class AsmUnit
    {
        public UnitKind Kind { get; init; }
        public string Name { get; init; } = "";
        public string Text { get; init; } = "";
    }

    /// <summary>
    /// Generates NASM source: 16-bit real mode for the Boot and Os units, 32-bit protected
    /// mode for the Kernel unit. Values are computed in eax; every variable lives at a fixed
    /// label. Library routines may change any general-purpose register, so nothing is kept in
    /// registers between statements, which also means every memory access really happens (as
    /// device memory needs).
    /// </summary>
    public sealed class X86Generator
    {
        /// <summary>Where the boot sector loads the 16-bit OS classes, right after itself.</summary>
        public const int OsAddress = 0x7E00;

        /// <summary>Where the loader puts a 32-bit kernel (see docs/memory-map.md).</summary>
        public const int KernelAddress = 0x10000;

        /// <summary>Where a user program runs, in its own address space.</summary>
        public const uint ProgramAddress = 0x40000000;

        readonly BoundProgram program;
        readonly BoundUnit unit;
        readonly DiagnosticBag diagnostics;
        readonly bool bits32;
        readonly string libraryTarget;

        readonly StringBuilder code = new();
        readonly HashSet<string> librarySymbols = new();
        readonly Dictionary<string, string> stringLabels = new();
        int labelCount;
        SourceFile file;
        (SourceFile?, int) lastComment;

        X86Generator(BoundProgram program, BoundUnit unit, DiagnosticBag diagnostics)
        {
            this.program = program;
            this.unit = unit;
            this.diagnostics = diagnostics;
            bits32 = unit.Kind is UnitKind.Kernel or UnitKind.Program;
            libraryTarget = Binder.TargetOf(unit.Kind);
            file = program.File;
        }

        public static AsmUnit Generate(BoundProgram program, BoundUnit unit, DiagnosticBag diagnostics)
        {
            var gen = new X86Generator(program, unit, diagnostics);
            return new AsmUnit
            {
                Kind = unit.Kind,
                Name = unit.Kind switch { UnitKind.Boot => "boot", UnitKind.Os => "os", UnitKind.Program => "program", _ => "kernel" },
                Text = gen.Build(),
            };
        }

        // ================================================================ layout

        string Build()
        {
            // every 32-bit kernel gets an interrupt table, so exceptions show the panic screen
            if (unit.Kind == UnitKind.Kernel) Need("phi_interrupts_init");

            // the program's own code first: it decides which library routines are needed
            foreach (ClassDecl cls in unit.Classes)
            {
                file = cls.File;
                Comment($"---- class {cls.Name}");
                foreach (Stmt s in cls.Body) EmitStatement(s);
            }

            Line("");
            Label("phi_halt");
            switch (unit.Kind)
            {
                case UnitKind.Program:
                    // the end of a program: exit with 0
                    Need("phi_exit");
                    Emit("xor ebx, ebx");
                    Emit("jmp phi_exit");
                    break;
                case UnitKind.Kernel:
                    // wait for interrupts, and let any programs run (int 48 = OS_Yield; a no-op until
                    // multitasking starts)
                    Emit("hlt");
                    Emit("int 48");
                    Emit("jmp phi_halt");
                    break;
                default:
                    Emit("hlt");
                    Emit("jmp phi_halt");
                    break;
            }

            foreach (MethodSymbol m in unit.Methods) EmitMethod(m);
            foreach (RawBlockDecl raw in unit.RawBlocks) EmitRawBlock(raw);

            List<LibraryFile> library = Library.Resolve(libraryTarget, librarySymbols.OrderBy(s => s));

            // events used by the library that the program doesn't handle
            var defined = unit.Methods.Select(m => m.Label).ToHashSet();
            foreach (string hook in library.SelectMany(f => f.Hooks).Distinct().Where(h => !defined.Contains(h)))
            {
                Line("");
                Label(hook);
                Emit("ret");
            }

            var output = new StringBuilder();
            string what = unit.Kind switch { UnitKind.Boot => "Boot sector", UnitKind.Os => "OS classes", UnitKind.Program => "User program", _ => "32-bit kernel" };
            output.AppendLine($"; {what} generated by phi from {Path.GetFileName(program.File.Path)}");

            switch (unit.Kind)
            {
                case UnitKind.Boot:
                    output.AppendLine("bits 16");
                    output.AppendLine("org 0x7C00");
                    output.AppendLine();
                    output.AppendLine("%ifndef PHI_KERNEL_SECTORS");
                    output.AppendLine("%define PHI_KERNEL_SECTORS 0");
                    output.AppendLine("%endif");
                    output.AppendLine();
                    output.AppendLine("    jmp 0x0000:phi_start    ; some BIOSes start us at 07C0:0000");
                    output.AppendLine("phi_start:");
                    output.AppendLine("    cli");
                    output.AppendLine("    xor ax, ax");
                    output.AppendLine("    mov ds, ax");
                    output.AppendLine("    mov es, ax");
                    output.AppendLine("    mov ss, ax");
                    output.AppendLine("    mov sp, 0x7C00          ; the stack grows down from just below us");
                    output.AppendLine("    sti");
                    output.AppendLine("    cld");
                    output.AppendLine("    mov [phi_boot_drive], dl");
                    break;

                case UnitKind.Os:
                    output.AppendLine("bits 16");
                    output.AppendLine($"org 0x{OsAddress:X}");
                    output.AppendLine();
                    output.AppendLine("phi_start:");
                    output.AppendLine("    cld");
                    break;

                case UnitKind.Program:
                    // the kernel starts us in ring 3 with our own address space and stack
                    output.AppendLine("bits 32");
                    output.AppendLine($"org 0x{ProgramAddress:X}");
                    output.AppendLine();
                    output.AppendLine("phi_start:");
                    output.AppendLine("    cld");
                    break;

                default:
                    // the loader has switched to protected mode with flat segments, set up a
                    // stack, and left the BootInfo address in ebx (see docs/memory-map.md)
                    output.AppendLine("bits 32");
                    output.AppendLine($"org 0x{KernelAddress:X}");
                    output.AppendLine();
                    output.AppendLine("phi_start:");
                    output.AppendLine("    cld");
                    break;
            }

            foreach (string init in library.SelectMany(f => f.Init))
                output.AppendLine($"    call {init}");

            output.Append(code);

            foreach (LibraryFile lib in library)
            {
                output.AppendLine();
                output.AppendLine($"; ---- library: {lib.Name}");
                output.Append(lib.Text);
            }

            output.AppendLine();
            // variables start on a page of their own: when code and the variables it writes share
            // a 4 KB page, QEMU throws away its translation of that code on every write, which made
            // hot loops run up to ~200 times slower
            if (bits32) output.AppendLine("align 4096, db 0");
            output.AppendLine("; ---- data");
            EmitData(output);

            if (unit.Kind == UnitKind.Boot)
            {
                output.AppendLine("phi_boot_drive: db 0");
                output.AppendLine();
                output.AppendLine("times 510 - ($ - $$) db 0   ; a negative size here means the boot sector is too big");
                output.AppendLine("dw 0xAA55");
            }

            return output.ToString();
        }

        // ================================================================ emit helpers

        void Emit(string instruction) => code.Append("    ").AppendLine(instruction);
        void Label(string label) => code.Append(label).AppendLine(":");
        void Line(string text) => code.AppendLine(text);
        string NewLabel(string hint) => $"phi_{hint}_{labelCount++}";

        void Comment(string text) => code.Append("    ; ").AppendLine(text);

        int LineOf(Node node) => file.GetLocation(node.Span.Start).Line;

        /// <summary>Puts the source line above the code it produced, which helps when reading the .asm.</summary>
        void SourceComment(Node node)
        {
            int line = LineOf(node);
            if (lastComment == (file, line)) return;
            lastComment = (file, line);

            string[] lines = file.Text.Split('\n');
            string text = line - 1 < lines.Length ? lines[line - 1].Trim() : "";
            code.AppendLine($"    ; {line}: {text}");
        }

        void Need(string librarySymbol) => librarySymbols.Add(librarySymbol);

        string StringLabel(string value)
        {
            if (!stringLabels.TryGetValue(value, out string? label))
            {
                label = $"phi_string_{stringLabels.Count}";
                stringLabels[value] = label;
            }
            return label;
        }

        // ================================================================ methods and asm blocks

        void EmitMethod(MethodSymbol m)
        {
            file = m.Decl.Owner.File;
            Line("");
            Comment(m.IsHook ? $"event {m.Name}" : m.IsInterruptHandler ? $"interrupt handler {m.Name}" : $"method {m.Name}");
            Label(m.Label);

            if (m.IsInterruptHandler)
            {
                // the interrupted code must find every register as it left it
                Emit("pushad");
                if (!bits32)
                {
                    Emit("push ds");
                    Emit("push es");
                    Emit("push fs");
                    Emit("xor ax, ax");
                    Emit("mov ds, ax");
                    Emit("mov es, ax");
                }
                Emit("cld");
            }

            foreach (Stmt s in m.Decl.Body) EmitStatement(s);

            if (m.Decl.Result != null)
            {
                SourceComment(m.Decl.Result);
                EmitExpr(m.Decl.Result); // the result goes back in eax
            }

            if (m.IsInterruptHandler)
            {
                if (!bits32)
                {
                    Emit("pop fs");
                    Emit("pop es");
                    Emit("pop ds");
                }
                Emit("popad");
                Emit(bits32 ? "iretd" : "iret");
            }
            else
            {
                Emit("ret");
            }
        }

        void EmitRawBlock(RawBlockDecl raw)
        {
            Line("");
            Comment($"asm.{raw.Name}");
            Label(raw.Name);

            var text = new StringBuilder();
            int i = 0;
            while (i < raw.Text.Length)
            {
                int open = raw.Text.IndexOf('{', i);
                int close = open < 0 ? -1 : raw.Text.IndexOf('}', open);
                if (close < 0) { text.Append(raw.Text, i, raw.Text.Length - i); break; }

                text.Append(raw.Text, i, open - i);
                string name = raw.Text[(open + 1)..close].Trim();

                string? replacement = ResolveAsmName(name);
                if (replacement != null) text.Append(replacement);
                else diagnostics.Error(raw.File, new Span(raw.TextSpan.Start + open, close - open + 1),
                        $"asm.{raw.Name} uses {{{name}}}, but there is no class variable or constant named '{name}'");

                i = close + 1;
            }

            foreach (string line in text.ToString().Replace("\r\n", "\n").Split('\n'))
                Line(line.TrimEnd());
        }

        /// <summary>{name} in an asm block: a variable's address, a field's address, or a constant's value.</summary>
        string? ResolveAsmName(string name)
        {
            string[] parts = name.Split('.');
            if (!unit.ClassNames.TryGetValue(parts[0], out Symbol? symbol))
                return Builtins.Constants.TryGetValue(name, out long builtin) ? builtin.ToString() : null;

            if (symbol is ConstantSymbol k) return parts.Length == 1 ? k.Value.ToString() : null;
            if (symbol is not VariableSymbol v) return null;

            int offset = 0;
            PhiType type = v.Type;
            foreach (string member in parts.Skip(1))
            {
                FieldSymbol? f = type.IsStruct ? type.Struct!.Find(member) : null;
                if (f == null) return null;
                offset += f.Offset;
                type = f.Type;
            }
            return offset == 0 ? v.Label : $"{v.Label} + {offset}";
        }

        // ================================================================ statements

        int unsafeDepth;

        void EmitStatement(Stmt stmt)
        {
            if (stmt is not (VarDecl { Symbol.NeedsInitCode: false } or ConstDecl or UnsafeStmt)) SourceComment(stmt);

            switch (stmt)
            {
                case VarDecl decl:
                    if (decl.Symbol is { NeedsInitCode: true } declared) EmitInitialize(declared, decl.Values);
                    break;

                case ConstDecl:
                    break;

                case LogStmt log:
                    EmitLog(log);
                    if (unit.Kind == UnitKind.Program && log.Target == LogTarget.ScreenAndSerial)
                    {
                        // a whole log statement reaches the screen at once, even with other programs running
                        Need("phi_flush");
                        Emit("call phi_flush");
                    }
                    break;

                case AskStmt ask:
                {
                    var v = (VariableSymbol)ask.Target.Symbol!;
                    Need("phi_read_line");
                    Emit($"mov edi, {v.Label}");
                    Emit($"mov ecx, {v.Capacity - 1}");
                    Emit("call phi_read_line");
                    break;
                }

                case ExitStmt exit when unit.Kind == UnitKind.Program:
                    if (exit.Code != null) EmitExpr(exit.Code);
                    else Emit("xor eax, eax");
                    Need("phi_exit");
                    Emit("mov ebx, eax            ; the exit code goes back to whoever waits for us");
                    Emit("jmp phi_exit");
                    break;

                case ExitStmt exit:
                    if (exit.Code != null) EmitExpr(exit.Code);
                    else Emit("xor eax, eax");
                    Emit("mov dx, 0xF4            ; QEMU isa-debug-exit");
                    Emit("out dx, al");
                    Emit("jmp phi_halt            ; not running in QEMU");
                    break;

                case OutStmt o:
                    if (ConstantFolder.Evaluate(o.Port) is long port)
                    {
                        EmitExpr(o.Value);
                        Emit($"mov dx, 0x{port & 0xFFFF:X}");
                    }
                    else
                    {
                        EmitExpr(o.Value);
                        Emit("push eax");
                        EmitExpr(o.Port);
                        Emit("mov dx, ax");
                        Emit("pop eax");
                    }
                    Emit(o.Size switch { 1 => "out dx, al", 2 => "out dx, ax", _ => "out dx, eax" });
                    break;

                case FreeStmt f:
                    EmitHeapCall(f.Releaser!, f.Pointer);
                    break;

                case UnsafeStmt u:
                    unsafeDepth++;
                    foreach (Stmt s in u.Body) EmitStatement(s);
                    unsafeDepth--;
                    break;

                case CallStmt call:
                    EmitCall(call);
                    break;

                case IfStmt ifs:
                {
                    string elseLabel = NewLabel("else");
                    string endLabel = NewLabel("endif");

                    EmitBranch(ifs.Condition, jumpIf: false, ifs.Else != null ? elseLabel : endLabel);
                    foreach (Stmt s in ifs.Then) EmitStatement(s);

                    if (ifs.Else != null)
                    {
                        Emit($"jmp {endLabel}");
                        Label(elseLabel);
                        foreach (Stmt s in ifs.Else) EmitStatement(s);
                    }

                    Label(endLabel);
                    break;
                }

                case WhileStmt loop:
                {
                    if (loop.Init?.Symbol != null) EmitInitialize(loop.Init.Symbol, loop.Init.Values);

                    string top = NewLabel("while");
                    string end = NewLabel("endwhile");

                    Label(top);
                    EmitBranch(loop.Condition, jumpIf: false, end);
                    foreach (Stmt s in loop.Body) EmitStatement(s);
                    if (loop.Step != null) EmitStatement(loop.Step);
                    Emit($"jmp {top}");
                    Label(end);
                    break;
                }

                case AssignStmt assign:
                    EmitAssign(assign.Target, assign.Value);
                    break;

                default:
                    throw new InvalidOperationException($"unexpected statement {stmt.GetType().Name}");
            }
        }

        static NameExpr NameOf(VariableSymbol v) => new() { Name = v.Name, Symbol = v, Type = v.Type };

        void EmitInitialize(VariableSymbol v, List<Expr> values)
        {
            // no value: zero, every time the declaration runs
            if (values.Count == 0)
            {
                if (v.Type.IsNumeric)
                {
                    Emit("xor eax, eax");
                    EmitStoreEax(NameOf(v));
                }
                else
                {
                    int size = StorageSize(v);
                    Emit($"mov edi, {v.Label}");
                    Emit($"mov ecx, {size}");
                    Emit("xor al, al");
                    Emit("rep stosb");
                }
                return;
            }

            if (!v.Type.IsArray)
            {
                EmitAssign(NameOf(v), values[0]);
                return;
            }

            for (int i = 0; i < values.Count; i++)
            {
                var element = new IndexExpr
                {
                    Target = NameOf(v),
                    Index = new NumberExpr { Value = i, Type = PhiType.Int },
                    Type = v.Type.Element,
                };
                EmitAssign(element, values[i]);
            }
        }

        void EmitLog(LogStmt log)
        {
            bool serialOnly = log.Target == LogTarget.SerialOnly;
            string suffix = serialOnly ? "_serial" : "";

            foreach (Expr value in log.Values)
            {
                // a ptr<u8> prints as the zero-terminated text it points to, like a str
                bool text = value.Type.IsString || (value.Type.IsPointer && value.Type.Pointee == PhiType.U8);
                if (text)
                {
                    string print = "phi_print" + suffix;
                    Need(print);
                    if (StaticAddress(value) is string label) Emit($"mov esi, {label}");
                    else
                    {
                        EmitExpr(value);
                        Emit("mov esi, eax");
                    }
                    Emit($"call {print}");
                }
                else
                {
                    string print = (value.Type.IsUnsigned32 ? "phi_print_uint" : "phi_print_int") + suffix;
                    Need(print);
                    EmitExpr(value);
                    Emit($"call {print}");
                }
            }
        }

        /// <summary>The label of a string whose address is known without running code.</summary>
        string? StaticAddress(Expr e) => e switch
        {
            StringExpr s => StringLabel(s.Value),
            NameExpr { Symbol: VariableSymbol { Type.IsString: true } v } => v.Label,
            _ => null,
        };

        void EmitCall(CallStmt call)
        {
            switch (call.Resolved)
            {
                case MethodSymbol method:
                {
                    // parameters are variables of the method: set each one, using its default when no argument is given
                    for (int i = 0; i < method.Parameters.Count; i++)
                    {
                        VariableSymbol p = method.Parameters[i];
                        Expr? value = i < call.Arguments.Count ? call.Arguments[i] : p.Decl.Values.FirstOrDefault();
                        if (value != null) EmitAssign(NameOf(p), value);
                        else if (i >= call.Arguments.Count) EmitInitialize(p, p.Decl.Values);
                    }
                    Emit($"call {method.Label}");
                    if (call.ResultTarget != null) EmitStoreResult(call.ResultTarget, method.ReturnType);
                    break;
                }

                case BuiltinFunction builtin:
                {
                    for (int i = call.Arguments.Count - 1; i >= 0; i--)
                    {
                        EmitExpr(call.Arguments[i]);
                        Emit("push eax");
                    }
                    Need(builtin.Label);
                    Emit($"call {builtin.Label}");
                    if (call.Arguments.Count > 0) Emit($"add {(bits32 ? "esp" : "sp")}, {call.Arguments.Count * 4}");
                    if (call.ResultTarget != null) EmitStoreResult(call.ResultTarget, PhiType.Int);
                    break;
                }

                case RawBlockDecl raw:
                    Emit($"call {raw.Name}");
                    if (call.ResultTarget != null) EmitStoreResult(call.ResultTarget, PhiType.Int);
                    break;
            }
        }

        /// <summary>Calls a one-parameter heap method (Heap.Alloc or Heap.Free) with a value.</summary>
        void EmitHeapCall(MethodSymbol method, Expr argument)
        {
            EmitAssign(NameOf(method.Parameters[0]), argument);
            Emit($"call {method.Label}");
        }

        /// <summary>Stores a call result (in eax) into a variable.</summary>
        void EmitStoreResult(Expr target, PhiType resultType)
        {
            if (target.Type.IsString) EmitStringStore(target, sourceIsString: resultType.IsString);
            else EmitStoreEax(target);
        }

        // ================================================================ memory places

        /// <summary>
        /// Where a value lives. Either a fixed address (Label + Offset), or Label + ebx + Offset
        /// when part of the address is computed, or, for memory reached through a pointer, a
        /// linear address in ebx (+ Offset) that may be anywhere in the first megabyte.
        /// </summary>
        sealed class Place
        {
            public string? Label;
            public int Offset;
            public bool Computed;   // ebx holds part of the address
            public bool Linear;     // ebx holds a linear address, not an offset from Label
        }

        Place EmitPlace(Expr e)
        {
            switch (e)
            {
                case NameExpr { Symbol: VariableSymbol v }:
                    return new Place { Label = v.Label };

                case NameExpr { Symbol: FieldPathSymbol f }:
                    return new Place { Label = f.Root.Label, Offset = f.Offset };

                case MemberExpr m:
                {
                    Place p = EmitPlace(m.Target);
                    p.Offset += m.Field!.Offset;
                    return p;
                }

                case IndexExpr ix:
                    return EmitIndexPlace(ix);
            }

            throw new InvalidOperationException($"{e.GetType().Name} has no address");
        }

        Place EmitIndexPlace(IndexExpr ix)
        {
            PhiType target = ix.Target.Type;
            int size = target.IsString ? 1 : target.IsPointer ? target.Pointee!.ElementSize : target.ElementSize;
            long? constant = ConstantFolder.Evaluate(ix.Index);

            // through a pointer, or the characters of a str that isn't a plain variable
            bool viaValue = target.IsPointer || (target.IsString && ix.Target is not NameExpr { Symbol: VariableSymbol });
            if (viaValue)
            {
                EmitExpr(ix.Target);

                if (constant != null)
                {
                    Emit("mov ebx, eax");
                    return new Place { Computed = true, Linear = true, Offset = (int)constant.Value * size };
                }
                Emit("push eax");
                EmitIndexValue(ix, size);
                Emit("pop ebx");
                Emit("add ebx, eax");
                return new Place { Computed = true, Linear = true };
            }

            Place p = EmitPlace(ix.Target);

            if (constant != null)
            {
                p.Offset += (int)constant.Value * size;
                return p;
            }

            if (p.Computed)
            {
                Emit("push ebx");
                EmitIndexValue(ix, size);
                Emit("pop ebx");
                Emit("add ebx, eax");
            }
            else
            {
                EmitIndexValue(ix, size);
                Emit("mov ebx, eax");
                p.Computed = true;
            }
            return p;
        }

        /// <summary>eax = index * size, after checking the index when needed.</summary>
        void EmitIndexValue(IndexExpr ix, int size)
        {
            EmitExpr(ix.Index);

            if (ix.CheckLimit is int limit && unsafeDepth == 0)
            {
                Need("phi_index_error");
                string ok = NewLabel("inbounds");
                Emit($"cmp eax, {limit}");
                Emit($"jb {ok}                ; unsigned, so negative indexes fail too");
                Emit($"mov eax, {LineOf(ix)}");
                Emit("jmp phi_index_error");
                Label(ok);
            }

            switch (size)
            {
                case 1: break;
                case 2: Emit("shl eax, 1"); break;
                case 4: Emit("shl eax, 2"); break;
                default: Emit($"imul eax, eax, {size}"); break;
            }
        }

        /// <summary>
        /// The memory operand for a place. In 16-bit code a linear address is reached through fs
        /// (which changes ecx); 32-bit memory is flat.
        /// </summary>
        string Operand(Place p)
        {
            string offset = p.Offset == 0 ? "" : p.Offset > 0 ? $" + {p.Offset}" : $" - {-p.Offset}";

            if (!p.Computed) return $"[{p.Label}{offset}]";
            if (!p.Linear) return $"[{p.Label} + ebx{offset}]";

            if (bits32) return $"[ebx{offset}]"; // memory is flat

            if (p.Offset != 0) Emit($"add ebx, {p.Offset}");
            Emit("mov ecx, ebx");
            Emit("shr ecx, 4");
            Emit("mov fs, cx               ; reach any address below 1 MB");
            Emit("and ebx, 0xF");
            return "[fs:ebx]";
        }

        /// <summary>How a value of this type sits in memory: str array elements are 32-bit pointers.</summary>
        static PhiType StorageType(PhiType t) => t.IsString ? PhiType.U32 : t;

        string LoadInstruction(PhiType type, string register, string operand)
        {
            PhiType t = StorageType(type);
            return t.ElementSize switch
            {
                1 => $"{(t.IsSigned ? "movsx" : "movzx")} {register}, byte {operand}",
                2 => $"{(t.IsSigned ? "movsx" : "movzx")} {register}, word {operand}",
                _ => $"mov {register}, dword {operand}",
            };
        }

        static string StoreInstruction(PhiType type, string operand) => StorageType(type).ElementSize switch
        {
            1 => $"mov byte {operand}, al",
            2 => $"mov word {operand}, ax",
            _ => $"mov dword {operand}, eax",
        };

        void EmitLoad(Expr e)
        {
            Place p = EmitPlace(e);
            Emit(LoadInstruction(e.Type, "eax", Operand(p)));
        }

        int StorageSize(VariableSymbol v) =>
            v.Type.IsString ? v.Capacity : v.Type.ElementSize * v.Count;

        // ================================================================ assignment

        void EmitAssign(Expr target, Expr value)
        {
            EmitExpr(value);
            if (target.Type.IsString) EmitStringStore(target, sourceIsString: value.Type.IsString);
            else EmitStoreEax(target);
        }

        /// <summary>Stores eax into a number variable, field or element.</summary>
        void EmitStoreEax(Expr target)
        {
            bool needsCode = !IsStaticPlace(target); // computing the address uses eax

            if (needsCode) Emit("push eax");
            Place p = EmitPlace(target);
            string operand = Operand(p);
            if (needsCode) Emit("pop eax");
            Emit(StoreInstruction(target.Type, operand));
        }

        /// <summary>True when the place's address is fixed, so computing it emits no code.</summary>
        static bool IsStaticPlace(Expr e) => e switch
        {
            NameExpr { Symbol: VariableSymbol or FieldPathSymbol } => true,
            MemberExpr m => IsStaticPlace(m.Target),
            IndexExpr ix => !ix.Target.Type.IsPointer && ConstantFolder.Evaluate(ix.Index) != null && IsStaticPlace(ix.Target)
                            && !(ix.Target.Type.IsString && ix.Target is not NameExpr),
            _ => false,
        };

        /// <summary>
        /// eax holds a string address (sourceIsString) or a number to write out as text;
        /// put it in a str variable or str array element, cut to fit.
        /// </summary>
        void EmitStringStore(Expr target, bool sourceIsString)
        {
            int capacity;
            if (target is NameExpr { Symbol: VariableSymbol v })
            {
                capacity = v.Capacity;
                Emit($"mov edi, {v.Label}");
            }
            else
            {
                // an element of a str array: its address is the element's value
                capacity = ((VariableSymbol)((NameExpr)((IndexExpr)target).Target).Symbol!).Capacity;
                Emit("push eax");
                EmitExpr(target);
                Emit("mov edi, eax");
                Emit("pop eax");
            }

            Emit($"mov ecx, {capacity}");
            if (sourceIsString)
            {
                Need("phi_strcpy");
                Emit("mov esi, eax");
                Emit("call phi_strcpy");
            }
            else
            {
                Need("phi_int_to_str");
                Emit("call phi_int_to_str");
            }
        }

        // ================================================================ expressions

        /// <summary>Leaves the value of <paramref name="e"/> in eax (strings: their address).</summary>
        void EmitExpr(Expr e)
        {
            if (e is BinaryExpr or UnaryExpr && ConstantFolder.Evaluate(e) is long folded)
            {
                LoadConstant("eax", folded);
                return;
            }

            switch (e)
            {
                case NumberExpr n:
                    LoadConstant("eax", n.Value);
                    break;

                case BoolExpr b:
                    LoadConstant("eax", b.Value ? 1 : 0);
                    break;

                case StringExpr s:
                    Emit($"mov eax, {StringLabel(s.Value)}");
                    break;

                case NameExpr { Symbol: VariableSymbol { Type.IsString: true } v }:
                    Emit($"mov eax, {v.Label}");
                    break;

                case NameExpr { Symbol: VariableSymbol or FieldPathSymbol }:
                    EmitLoad(e);
                    break;

                case NameExpr { Symbol: ConstantSymbol k }:
                    LoadConstant("eax", k.Value);
                    break;

                case NameExpr { Symbol: LengthSymbol { Count: int count } }:
                    LoadConstant("eax", count);
                    break;

                case NameExpr { Symbol: LengthSymbol { Str: VariableSymbol str } }:
                    Need("phi_strlen");
                    Emit($"mov esi, {str.Label}");
                    Emit("call phi_strlen");
                    break;

                case IndexExpr or MemberExpr:
                    EmitLoad(e);
                    break;

                case AddrExpr addr:
                    EmitAddress(addr);
                    break;

                case NewExpr n:
                    EmitHeapCall(n.Allocator!, n.Bytes); // the address comes back in eax
                    break;

                case InExpr input:
                    if (ConstantFolder.Evaluate(input.Port) is long port) Emit($"mov dx, 0x{port & 0xFFFF:X}");
                    else
                    {
                        EmitExpr(input.Port);
                        Emit("mov dx, ax");
                    }
                    switch (input.Size)
                    {
                        case 1: Emit("in al, dx"); Emit("movzx eax, al"); break;
                        case 2: Emit("in ax, dx"); Emit("movzx eax, ax"); break;
                        default: Emit("in eax, dx"); break;
                    }
                    break;

                case UnaryExpr unary:
                    EmitExpr(unary.Operand);
                    switch (unary.Op)
                    {
                        case UnaryOp.Negate: Emit("neg eax"); break;
                        case UnaryOp.BitNot: Emit("not eax"); break;
                        default:
                            Emit("test eax, eax");
                            Emit("sete al");
                            Emit("movzx eax, al");
                            break;
                    }
                    break;

                case BinaryExpr { IsComparison: true } or BinaryExpr { IsLogical: true }:
                {
                    string falseLabel = NewLabel("false");
                    string endLabel = NewLabel("bool");
                    EmitBranch(e, jumpIf: false, falseLabel);
                    Emit("mov eax, 1");
                    Emit($"jmp {endLabel}");
                    Label(falseLabel);
                    Emit("xor eax, eax");
                    Label(endLabel);
                    break;
                }

                case BinaryExpr binary:
                    EmitArithmetic(binary);
                    break;

                default:
                    throw new InvalidOperationException($"unexpected expression {e.GetType().Name}");
            }
        }

        void EmitAddress(AddrExpr addr)
        {
            if (addr.CodeLabel != null)
            {
                Emit($"mov eax, {addr.CodeLabel}");
                return;
            }

            if (addr.Operand is NameExpr { Symbol: VariableSymbol v })
            {
                Emit($"mov eax, {v.Label}");
                return;
            }

            Place p = EmitPlace(addr.Operand);
            string offset = p.Offset == 0 ? "" : $" + {p.Offset}";
            if (!p.Computed) Emit($"mov eax, {p.Label}{offset}");
            else if (!p.Linear) Emit($"lea eax, [{p.Label} + ebx{offset}]");
            else Emit($"lea eax, [ebx{offset}]");
        }

        void EmitArithmetic(BinaryExpr binary)
        {
            bool unsigned = binary.Type.IsUnsigned32;
            EmitOperands(binary);

            switch (binary.Op)
            {
                case BinaryOp.Add: Emit("add eax, ecx"); break;
                case BinaryOp.Subtract: Emit("sub eax, ecx"); break;
                case BinaryOp.Multiply: Emit("imul eax, ecx"); break;
                case BinaryOp.BitAnd: Emit("and eax, ecx"); break;
                case BinaryOp.BitOr: Emit("or eax, ecx"); break;
                case BinaryOp.BitXor: Emit("xor eax, ecx"); break;
                case BinaryOp.ShiftLeft: Emit("shl eax, cl"); break;
                case BinaryOp.ShiftRight: Emit(unsigned ? "shr eax, cl" : "sar eax, cl"); break;
                case BinaryOp.Divide:
                case BinaryOp.Modulo:
                    if (unsigned)
                    {
                        Emit("xor edx, edx");
                        Emit("div ecx");
                    }
                    else
                    {
                        Emit("cdq");
                        Emit("idiv ecx");
                    }
                    if (binary.Op == BinaryOp.Modulo) Emit("mov eax, edx");
                    break;
            }
        }

        void LoadConstant(string register, long value)
        {
            if (value == 0) Emit($"xor {register}, {register}");
            else Emit($"mov {register}, {(int)value}");
        }

        /// <summary>Left operand in eax, right operand in ecx.</summary>
        void EmitOperands(BinaryExpr b)
        {
            if (TryLoadSimple(b.Right, "ecx", dryRun: true))
            {
                EmitExpr(b.Left);
                TryLoadSimple(b.Right, "ecx", dryRun: false);
                return;
            }

            EmitExpr(b.Right);
            Emit("push eax");
            EmitExpr(b.Left);
            Emit("pop ecx");
        }

        /// <summary>Loads values that need no other registers straight into a register.</summary>
        bool TryLoadSimple(Expr e, string register, bool dryRun)
        {
            string? instruction = ConstantFolder.Evaluate(e) is long k
                ? (k == 0 ? $"xor {register}, {register}" : $"mov {register}, {(int)k}")
                : e switch
                {
                    StringExpr s => $"mov {register}, {StringLabel(s.Value)}",
                    NameExpr { Symbol: VariableSymbol { Type.IsString: true } v } => $"mov {register}, {v.Label}",
                    NameExpr { Symbol: VariableSymbol { Type.IsNumeric: true } v } => LoadInstruction(v.Type, register, $"[{v.Label}]"),
                    NameExpr { Symbol: FieldPathSymbol { Type.IsNumeric: true } f } =>
                        LoadInstruction(f.Type, register, f.Offset == 0 ? $"[{f.Root.Label}]" : $"[{f.Root.Label} + {f.Offset}]"),
                    _ => null,
                };

            if (instruction == null) return false;
            if (!dryRun) Emit(instruction);
            return true;
        }

        /// <summary>Jumps to <paramref name="target"/> when the condition's truth equals <paramref name="jumpIf"/>.</summary>
        void EmitBranch(Expr condition, bool jumpIf, string target)
        {
            if (ConstantFolder.Evaluate(condition) is long known)
            {
                if ((known != 0) == jumpIf) Emit($"jmp {target}");
                return;
            }

            switch (condition)
            {
                case UnaryExpr { Op: UnaryOp.Not } not:
                    EmitBranch(not.Operand, !jumpIf, target);
                    return;

                case BinaryExpr { Op: BinaryOp.And } and:
                    if (jumpIf)
                    {
                        string skip = NewLabel("and");
                        EmitBranch(and.Left, false, skip);
                        EmitBranch(and.Right, true, target);
                        Label(skip);
                    }
                    else
                    {
                        EmitBranch(and.Left, false, target);
                        EmitBranch(and.Right, false, target);
                    }
                    return;

                case BinaryExpr { Op: BinaryOp.Or } or:
                    if (jumpIf)
                    {
                        EmitBranch(or.Left, true, target);
                        EmitBranch(or.Right, true, target);
                    }
                    else
                    {
                        string skip = NewLabel("or");
                        EmitBranch(or.Left, true, skip);
                        EmitBranch(or.Right, false, target);
                        Label(skip);
                    }
                    return;

                case BinaryExpr { IsComparison: true, Left.Type.IsString: true, Right.Type.IsString: true } cmp:
                {
                    Need("phi_strcmp");
                    EmitExpr(cmp.Right);
                    Emit("push eax");
                    EmitExpr(cmp.Left);
                    Emit("mov esi, eax");
                    Emit("pop edi");
                    Emit("call phi_strcmp          ; eax = 0 when equal");
                    Emit("test eax, eax");
                    bool equalWanted = (cmp.Op == BinaryOp.Equal) == jumpIf;
                    Emit($"{(equalWanted ? "jz" : "jnz")} {target}");
                    return;
                }

                case BinaryExpr { IsComparison: true } cmp:
                {
                    bool unsigned = cmp.Left.Type.IsUnsigned32 || cmp.Right.Type.IsUnsigned32;
                    EmitOperands(cmp);
                    Emit("cmp eax, ecx");
                    BinaryOp op = jumpIf ? cmp.Op : Invert(cmp.Op);
                    string jump = op switch
                    {
                        BinaryOp.Equal => "je",
                        BinaryOp.NotEqual => "jne",
                        BinaryOp.Less => unsigned ? "jb" : "jl",
                        BinaryOp.LessEqual => unsigned ? "jbe" : "jle",
                        BinaryOp.Greater => unsigned ? "ja" : "jg",
                        _ => unsigned ? "jae" : "jge",
                    };
                    Emit($"{jump} {target}");
                    return;
                }
            }

            EmitExpr(condition);
            Emit("test eax, eax");
            Emit($"{(jumpIf ? "jnz" : "jz")} {target}");
        }

        static BinaryOp Invert(BinaryOp op) => op switch
        {
            BinaryOp.Equal => BinaryOp.NotEqual,
            BinaryOp.NotEqual => BinaryOp.Equal,
            BinaryOp.Less => BinaryOp.GreaterEqual,
            BinaryOp.LessEqual => BinaryOp.Greater,
            BinaryOp.Greater => BinaryOp.LessEqual,
            _ => BinaryOp.Less,
        };

        // ================================================================ data

        void EmitData(StringBuilder output)
        {
            foreach (VariableSymbol v in unit.Variables.Distinct())
            {
                if (v.Type.IsError) continue;
                output.Append(DataFor(v));
            }

            foreach (var (value, label) in stringLabels)
                output.AppendLine($"{label}: db {NasmBytes(value)}");
        }

        string DataFor(VariableSymbol v)
        {
            var sb = new StringBuilder();
            List<object>? values = v.StaticValues;
            PhiType t = v.Type;

            if (t.IsString)
            {
                string text = values is [var first] ? AsText(first) : "";
                AppendString(sb, v.Label, text, v.Capacity);
                return sb.ToString();
            }

            if (t.Kind == TypeKind.Str)
            {
                var pointers = new List<string>();
                for (int i = 0; i < v.Count; i++)
                {
                    string element = $"{v.Label}__{i}";
                    pointers.Add(element);
                    string text = values != null && i < values.Count ? AsText(values[i]) : "";
                    AppendString(sb, element, text, v.Capacity);
                }
                sb.AppendLine($"{v.Label}: dd {string.Join(", ", pointers)}");
                return sb.ToString();
            }

            if (t.Kind == TypeKind.Struct)
            {
                sb.AppendLine($"{v.Label}: times {StorageSize(v)} db 0   ; {t}");
                return sb.ToString();
            }

            string directive = t.ElementSize switch { 1 => "db", 2 => "dw", _ => "dd" };
            if (values == null || values.Count == 0)
            {
                sb.AppendLine(v.Count == 1 ? $"{v.Label}: {directive} 0" : $"{v.Label}: times {v.Count} {directive} 0");
                return sb.ToString();
            }

            long mask = t.ElementSize switch { 1 => 0xFF, 2 => 0xFFFF, _ => 0xFFFFFFFF };
            var numbers = values.Select(x => x is long n ? n & mask : 0).Select(n => n.ToString());
            sb.AppendLine($"{v.Label}: {directive} {string.Join(", ", numbers)}");
            if (values.Count < v.Count) sb.AppendLine($"    times {v.Count - values.Count} {directive} 0");
            return sb.ToString();
        }

        /// <summary>A constant destined for a str: text as-is, numbers written in decimal.</summary>
        static string AsText(object value) => value switch
        {
            string s => s,
            long n => ((int)n).ToString(),
            _ => "",
        };

        static void AppendString(StringBuilder sb, string label, string text, int capacity)
        {
            if (text.Length + 1 > capacity) text = text[..Math.Max(capacity - 1, 0)];
            sb.AppendLine($"{label}: db {NasmBytes(text)}");
            int padding = capacity - text.Length - 1;
            if (padding > 0) sb.AppendLine($"    times {padding} db 0");
        }

        /// <summary>'Hello', 13, 10, 0 — printable text quoted, everything else as numbers.</summary>
        static string NasmBytes(string text)
        {
            var parts = new List<string>();
            var run = new StringBuilder();

            void Flush()
            {
                if (run.Length == 0) return;
                parts.Add($"'{run}'");
                run.Clear();
            }

            foreach (char c in text)
            {
                if (c >= 0x20 && c < 0x7F && c != '\'') run.Append(c);
                else
                {
                    Flush();
                    parts.Add(c < 256 ? ((int)c).ToString() : "'?'");
                }
            }

            Flush();
            parts.Add("0");
            return string.Join(", ", parts);
        }
    }
}
